name: Deep CNCF CI
on:
  push:
    paths:
      - '/test/unit/**'
  workflow_dispatch:
jobs:
  build:
    if: github.repository == 'amosproj/amos2024ss08-cloud-native-llm' # Don't do this in forks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover -p webpage_extractor_test.py
